---
# tasks file for subversion

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: subversion

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: subversion

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: subversion
