---
# tasks file for subversion (Ubuntu specific)

- name: Install subversion packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: subversion_packages
  tags: subversion
